version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:4.0.2-management
    container_name: rabbitmq-warehouse-data-analyzer
    restart: unless-stopped
    env_file: .env
    ports:
      - ${RMQ_PORT}:${RMQ_PORT}
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RMQ_PASSWORD}

  fastapi:
    build: ./
    container_name: warehouse-data-analyzer
    depends_on:
      - rabbitmq
    expose:
      - 8000
    env_file: .env
    environment:
      - RMQ_URL=amqp://${RMQ_USER}:${RMQ_PASSWORD}@rabbitmq:${RMQ_PORT}

  nginx:
    image: nginx:latest
    container_name: nginx-warehouse-data-analyzer
    restart: unless-stopped
    depends_on:
      - fastapi
    ports:
      - 80:80
    volumes:
      - ./app/configuration/nginx/default.conf:/etc/nginx/conf.d/default.conf
